### ISSUE TITLE
Vocindex interval

### ISSUE THREAD

**Issue by remyhx** [Sensirion/arduino-i2c-sgp40#1]
Hi, in case of usage in ultra low powered iot; for the vocindex a 1hz datastream is necessary to build a reliable vocindex. Is it possible to do per (same constant) 5 minutes? Or does this really change the vocindex readout?

**Comment by MBjoern** [comment]
Hi remyhx,

The algorithm expects a one second interval, and all the internal parameters are configured for this particular parameters. 
Please contact info@sensirion.com for more particular questions about measuring VOC in general.
