### ISSUE TITLE
Error: Not enough data received

### ISSUE THREAD

**Issue by tritdm** [Sensirion/arduino-i2c-sgp40#2]
Hello, 
I'm trying this library and it's example to test SGP40 and I received this error:
![image](https://github.com/Sensirion/arduino-i2c-sgp40/assets/91335704/f77572c0-087d-47f6-b371-2375d23b68a3)
But when I used this [snnipet](https://github.com/Sensirion/arduino-snippets/blob/main/SGP40_SHTC3_I2C_voc_algo_minimal_example/SGP40_SHTC3_I2C_voc_algo_minimal_example.ino), it returned values:
![image](https://github.com/Sensirion/arduino-i2c-sgp40/assets/91335704/c84e7f9e-8a6a-4473-b239-222661e727a3)
## Update: although the snippet can return values, it kept only one value (not change based on environment) and it seems random (different values for resets at same environment)
Can you help me

**Comment by LeonieFierz** [comment]
"Not enough data received" is usually an issue with the sensor connection. E.g. there is too much noise or the i2c signal is out of specs.
How do you connect the SGP to your Arduino Board? 
You find information about the recommended circuit in the datasheet https://sensirion.com/media/documents/296373BB/6203C5DF/Sensirion_Gas_Sensors_Datasheet_SGP40.pdf Chapter "2.5 Hardware Interface Specification".

**Comment by tritdm** [comment]
> How do you connect the SGP to your Arduino Board?

![image](https://github.com/Sensirion/arduino-i2c-sgp40/assets/91335704/f41dadd3-7098-4a29-a268-b0c20723ee85)
![image](https://github.com/Sensirion/arduino-i2c-sgp40/assets/91335704/b0c396d5-c256-4262-a8b2-83040805be2b)
![image](https://github.com/Sensirion/arduino-i2c-sgp40/assets/91335704/3aedd5db-e982-4617-8bf2-f4c4fcba9170)
This is my schematic. I use a PCB board with multiple integrated sensors. Does this cause issues?

## Update: Sorry for my carelessness, I realize I don't enable the PWR_EN pin. Now I get the logs (SRAW_VOC), can we use the algorithm in the snippet to calculate the VOC index?

**Comment by LeonieFierz** [comment]
Good to hear that it worked out now.
For calculating VOC Index you can use the arduino library https://github.com/Sensirion/arduino-gas-index-algorithm/.
There you find example usages as a reference how to use the library.

**Comment by tritdm** [comment]
Thank you very much for helping!
